# Generated by Django 2.1.4 on 2018-12-27 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0001_initial'),
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.IntegerField()),
                ('CurrencyUnit', models.CharField(default='INR', max_length=10)),
                ('PaidAmount', models.IntegerField()),
                ('ReciptNumber', models.CharField(max_length=70, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('PaidBy', models.CharField(choices=[('S', 'Student'), ('P', 'Parent'), ('O', 'Others')], max_length=30)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.User')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Student.Student')),
            ],
        ),
    ]
