# Generated by Django 2.1.4 on 2018-12-28 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='CurrencyUnit',
        ),
    ]
