# Generated by Django 2.1.4 on 2018-12-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90, unique=True)),
                ('password', models.CharField(max_length=400)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff'), ('ADMIN', 'Admin'), ('PARENT', 'Parent'), ('TEACHER', 'Teacher')], max_length=30)),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
                ('LastActivity', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
