# Generated by Django 2.1.4 on 2019-01-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='LastActivity',
        ),
    ]
