# Generated by Django 2.1.4 on 2019-01-10 09:50

import Staff.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_remove_user_lastactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('FirstName', models.CharField(max_length=90)),
                ('LastName', models.CharField(max_length=90)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Phone', models.PositiveIntegerField(blank=True)),
                ('createdAt', models.DateField(auto_now=True)),
                ('Image', models.ImageField(blank=True, upload_to=Staff.models.image_path)),
                ('BloodGroup', models.CharField(blank=True, choices=[('O+', 'O Positve'), ('O-', 'O Negetive'), ('B+', 'B Postive'), ('B-', 'B Negetive'), ('A+', 'A Postive'), ('A-', 'A Negetive'), ('AB+', 'AB Postive'), ('AB-', 'AB Negetive')], max_length=13)),
                ('FatherName', models.CharField(blank=True, max_length=181)),
                ('MotherName', models.CharField(blank=True, max_length=181)),
                ('Address', models.TextField(blank=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', unique=True)),
            ],
        ),
    ]
