# Generated by Django 2.1.4 on 2018-12-28 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '__first__'),
        ('ClassApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmodel',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Teacher.Teacher'),
        ),
    ]
