# Generated by Django 2.1.4 on 2018-12-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20181227_1531'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendence',
            unique_together={('student', 'Date')},
        ),
    ]
