# Generated by Django 2.1.4 on 2018-12-28 08:15

import Student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20181227_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_passedout',
        ),
        migrations.AddField(
            model_name='student',
            name='Image',
            field=models.ImageField(blank=True, upload_to=Student.models.images_path),
        ),
    ]
