# Generated by Django 2.1.4 on 2018-12-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=200)),
                ('years', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=181)),
                ('FirstName', models.CharField(max_length=90)),
                ('LastName', models.CharField(max_length=90)),
                ('PhoneNumber', models.IntegerField()),
                ('DOB', models.DateField(blank=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('image_path', models.CharField(blank=True, max_length=200)),
                ('BloodGroup', models.CharField(blank=True, choices=[('O+', 'O Positve'), ('O-', 'O Negetive'), ('B+', 'B Postive'), ('B-', 'B Negetive'), ('A+', 'A Postive'), ('A-', 'A Negetive'), ('AB+', 'AB Postive'), ('AB-', 'AB Negetive')], max_length=13)),
                ('FatherName', models.CharField(blank=True, max_length=181)),
                ('MotherName', models.CharField(blank=True, max_length=181)),
                ('Address', models.TextField(blank=True)),
                ('Experience', models.ManyToManyField(blank=True, to='Teacher.Experience')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
