# Generated by Django 2.1.4 on 2019-01-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_auto_20181228_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='PhoneNumber',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', unique=True),
        ),
    ]
