# Generated by Django 2.1.4 on 2019-01-10 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_auto_20190110_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='User',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
